<a href="https://colab.research.google.com/github/Pameta1/TelecomX_2/blob/main/TelecomX_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [216]:
import pandas as pd

In [217]:
datos_cliente = pd.read_csv('/content/datos_tratados.csv')

In [218]:
datos_cliente.head(2)

,CustomerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Cuentas_Diarias,Churn_bin
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3,2.186667,0.0
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4,1.996667,0.0

In [219]:
columnas_a_eliminar = ['CustomerID', 'Churn']

In [220]:
datos_cliente.head(2)

,CustomerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Cuentas_Diarias,Churn_bin
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3,2.186667,0.0
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4,1.996667,0.0

In [221]:
# Separar variables predictoras y objetivo
X = datos_cliente.drop('Churn_bin', axis=1)
y = datos_cliente['Churn_bin']

In [222]:
datos_cliente['Churn_bin'].isna().sum()

np.int64(224)

In [223]:
datos_cliente[datos_cliente['Churn_bin'].isna()]

,CustomerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Cuentas_Diarias,Churn_bin
30,0047-ZHDTW,NaN,Female,0,No,No,11,Yes,Yes,Fiber optic,...,No,No,No,Month-to-month,Yes,Bank transfer (automatic),79.00,929.30,2.633333,NaN
75,0120-YZLQA,NaN,Male,0,No,No,71,Yes,No,No,...,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),19.90,1355.10,0.663333,NaN
96,0154-QYHJU,NaN,Male,0,No,No,29,Yes,No,DSL,...,Yes,No,No,One year,Yes,Electronic check,58.75,1696.20,1.958333,NaN
98,0162-RZGMZ,NaN,Female,1,No,No,5,Yes,No,DSL,...,Yes,No,No,Month-to-month,No,Credit card (automatic),59.90,287.85,1.996667,NaN
175,0274-VVQOQ,NaN,Male,1,Yes,No,65,Yes,Yes,Fiber optic,...,No,Yes,Yes,One year,Yes,Bank transfer (automatic),103.15,6792.45,3.438333,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7158,9840-GSRFX,NaN,Female,0,No,No,14,Yes,Yes,DSL,...,No,No,No,One year,Yes,Mailed check,54.25,773.20,1.808333,NaN
7180,9872-RZQQB,NaN,Female,0,Yes,No,49,No,No phone service,DSL,...,No,Yes,No,Month-to-month,No,Bank transfer (automatic),40.65,2070.75,1.355000,NaN
7211,9920-GNDMB,NaN,Male,0,No,No,9,Yes,Yes,Fiber optic,...,No,No,No,Month-to-month,Yes,Electronic check,76.25,684.85,2.541667,NaN
7239,9955-RVWSC,NaN,Female,0,Yes,Yes,67,Yes,No,No,...,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),19.25,1372.90,0.641667,NaN
7247,9966-VYRTZ,NaN,Female,0,Yes,Yes,31,Yes,No,No,...,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,19.55,658.95,0.651667,NaN

In [224]:
datos_cliente = datos_cliente.dropna(subset=['Churn_bin'])

In [225]:
X = datos_cliente.drop('Churn_bin', axis=1)
y = datos_cliente['Churn_bin']

In [226]:
# Dividir train-test

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42, stratify=y)

In [227]:
 # Pipeline de preprocesamiento
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

numericas = X.select_dtypes(include=['int64', 'float64']).columns
categoricas = X.select_dtypes(include=['object']).columns

preprocesador = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numericas),
        ('cat', OneHotEncoder(drop='first'), categoricas)
    ]
)